name: Set up build environment
description: Prepares environment for building with JDK and Gradle
runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3
