language: "en"
early_access: false
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/sample/**"
    - "!**/samples/**"
    - "!**/sampleApp/**"
    - "!**/sample-app/**"
    - "!*.xml"
    - "!*.svg"
    - "!**/config/detekt.yml"
    - "!**/.run/**"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
chat:
  auto_reply: true
