package dev.tonholo.s2c.domain.svg

import dev.tonholo.s2c.domain.compose.ComposeColor
import kotlin.jvm.JvmInline

@JvmInline
value class SvgColor private constructor(val value: String) {
    companion object {
        operator fun invoke(value: String): SvgColor = SvgColor(
            namedColors[value] ?: value
        )
    }
}

/**
 * @return black color when [SvgColor] is `null`.
 */
fun SvgColor?.orDefault(): SvgColor = this ?: SvgColor("black")

fun SvgColor.toComposeColor(): ComposeColor = ComposeColor(value)

/**
 * @see <a href="http://www.w3.org/TR/SVG11/single-page.html#types-ColorKeywords">W3 Color Keywords</a>
 */
private val namedColors = mapOf(
    "aliceblue" to "#FFF0F8FF",
    "antiquewhite" to "#FFFAEBD7",
    "aqua" to "#FF00FFFF",
    "aquamarine" to "#FF7FFFD4",
    "azure" to "#FFF0FFFF",
    "beige" to "#FFF5F5DC",
    "bisque" to "#FFFFE4C4",
    "black" to "#FF000000",
    "blanchedalmond" to "#FFFFEBCD",
    "blue" to "#FF0000FF",
    "blueviolet" to "#FF8A2BE2",
    "brown" to "#FFA52A2A",
    "burlywood" to "#FFDEB887",
    "cadetblue" to "#FF5F9EA0",
    "chartreuse" to "#FF7FFF00",
    "chocolate" to "#FFD2691E",
    "coral" to "#FFFF7F50",
    "cornflowerblue" to "#FF6495ED",
    "cornsilk" to "#FFFFF8DC",
    "crimson" to "#FFDC143C",
    "cyan" to "#FF00FFFF",
    "darkblue" to "#FF00008B",
    "darkcyan" to "#FF008B8B",
    "darkgoldenrod" to "#FFB8860B",
    "darkgray" to "#FFA9A9A9",
    "darkgreen" to "#FF006400",
    "darkgrey" to "#FFA9A9A9",
    "darkkhaki" to "#FFBDB76B",
    "darkmagenta" to "#FF8B008B",
    "darkolivegreen" to "#FF556B2F",
    "darkorange" to "#FFFF8C00",
    "darkorchid" to "#FF9932CC",
    "darkred" to "#FF8B0000",
    "darksalmon" to "#FFE9967A",
    "darkseagreen" to "#FF8FBC8F",
    "darkslateblue" to "#FF483D8B",
    "darkslategray" to "#FF2F4F4F",
    "darkslategrey" to "#FF2F4F4F",
    "darkturquoise" to "#FF00CED1",
    "darkviolet" to "#FF9400D3",
    "deeppink" to "#FFFF1493",
    "deepskyblue" to "#FF00BFFF",
    "dimgray" to "#FF696969",
    "dimgrey" to "#FF696969",
    "dodgerblue" to "#FF1E90FF",
    "firebrick" to "#FFB22222",
    "floralwhite" to "#FFFFFAF0",
    "forestgreen" to "#FF228B22",
    "fuchsia" to "#FFFF00FF",
    "gainsboro" to "#FFDCDCDC",
    "ghostwhite" to "#FFF8F8FF",
    "gold" to "#FFFFD700",
    "goldenrod" to "#FFDAA520",
    "gray" to "#FF808080",
    "green" to "#FF008000",
    "greenyellow" to "#FFADFF2F",
    "grey" to "#FF808080",
    "honeydew" to "#FFF0FFF0",
    "hotpink" to "#FFFF69B4",
    "indianred" to "#FFCD5C5C",
    "indigo" to "#FF4B0082",
    "ivory" to "#FFFFFFF0",
    "khaki" to "#FFF0E68C",
    "lavender" to "#FFE6E6FA",
    "lavenderblush" to "#FFFFF0F5",
    "lawngreen" to "#FF7CFC00",
    "lemonchiffon" to "#FFFFFACD",
    "lightblue" to "#FFADD8E6",
    "lightcoral" to "#FFF08080",
    "lightcyan" to "#FFE0FFFF",
    "lightgoldenrodyellow" to "#FFFAFAD2",
    "lightgray" to "#FFD3D3D3",
    "lightgreen" to "#FF90EE90",
    "lightgrey" to "#FFD3D3D3",
    "lightpink" to "#FFFFB6C1",
    "lightsalmon" to "#FFFFA07A",
    "lightseagreen" to "#FF20B2AA",
    "lightskyblue" to "#FF87CEFA",
    "lightslategray" to "#FF778899",
    "lightslategrey" to "#FF778899",
    "lightsteelblue" to "#FFB0C4DE",
    "lightyellow" to "#FFFFFFE0",
    "lime" to "#FF00FF00",
    "limegreen" to "#FF32CD32",
    "linen" to "#FFFAF0E6",
    "magenta" to "#FFFF00FF",
    "maroon" to "#FF800000",
    "mediumaquamarine" to "#FF66CDAA",
    "mediumblue" to "#FF0000CD",
    "mediumorchid" to "#FFBA55D3",
    "mediumpurple" to "#FF9370DB",
    "mediumseagreen" to "#FF3CB371",
    "mediumslateblue" to "#FF7B68EE",
    "mediumspringgreen" to "#FF00FA9A",
    "mediumturquoise" to "#FF48D1CC",
    "mediumvioletred" to "#FFC71585",
    "midnightblue" to "#FF191970",
    "mintcream" to "#FFF5FFFA",
    "mistyrose" to "#FFFFE4E1",
    "moccasin" to "#FFFFE4B5",
    "navajowhite" to "#FFFFDEAD",
    "navy" to "#FF000080",
    "oldlace" to "#FFFDF5E6",
    "olive" to "#FF808000",
    "olivedrab" to "#FF6B8E23",
    "orange" to "#FFFFA500",
    "orangered" to "#FFFF4500",
    "orchid" to "#FFDA70D6",
    "palegoldenrod" to "#FFEEE8AA",
    "palegreen" to "#FF98FB98",
    "paleturquoise" to "#FFAFEEEE",
    "palevioletred" to "#FFDB7093",
    "papayawhip" to "#FFFFEFD5",
    "peachpuff" to "#FFFFDAB9",
    "peru" to "#FFCD853F",
    "pink" to "#FFFFC0CB",
    "plum" to "#FFDDA0DD",
    "powderblue" to "#FFB0E0E6",
    "purple" to "#FF800080",
    "rebeccapurple" to "#FF663399",
    "red" to "#FFFF0000",
    "rosybrown" to "#FFBC8F8F",
    "royalblue" to "#FF4169E1",
    "saddlebrown" to "#FF8B4513",
    "salmon" to "#FFFA8072",
    "sandybrown" to "#FFF4A460",
    "seagreen" to "#FF2E8B57",
    "seashell" to "#FFFFF5EE",
    "sienna" to "#FFA0522D",
    "silver" to "#FFC0C0C0",
    "skyblue" to "#FF87CEEB",
    "slateblue" to "#FF6A5ACD",
    "slategray" to "#FF708090",
    "slategrey" to "#FF708090",
    "snow" to "#FFFFFAFA",
    "springgreen" to "#FF00FF7F",
    "steelblue" to "#FF4682B4",
    "tan" to "#FFD2B48C",
    "teal" to "#FF008080",
    "thistle" to "#FFD8BFD8",
    "tomato" to "#FFFF6347",
    "turquoise" to "#FF40E0D0",
    "violet" to "#FFEE82EE",
    "wheat" to "#FFF5DEB3",
    "white" to "#FFFFFFFF",
    "whitesmoke" to "#FFF5F5F5",
    "yellow" to "#FFFFFF00",
    "yellowgreen" to "#FF9ACD32",
)
