name: Set up NodeJS environment
description: Prepares environment for NodeJS
inputs:
  os:
    description: The runner os
    required: true
  svgo-version:
    description: SVGO major or exact version to install
    required: false
    default: "4"
  avocado-version:
    description: Avocado major or exact version to install
    required: false
    default: "1"
runs:
  using: 'composite'
  steps:
    - name: Restore NPM cache
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm/**/*
        key: npm-cache-${{ inputs.os }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install global dependencies
      shell: bash
      run: |
        npm -g install \
          "svgo@${{ inputs.svgo-version }}" \
          "avocado@${{ inputs.avocado-version }}"
