name: CLI Integrity check
description: Runs the CLI command checking if it still works as intended
runs:
  using: composite
  steps:
    - name: Verify simple svg conversion without optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/ShieldSolid.NonOptimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=false \
              samples/shield-halved-solid.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff integrity-check/ShieldSolid.NonOptimized.kt samples/ShieldSolid.nonoptimized.kt
        if [[ -z "$?" ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify simple svg conversion with optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/ShieldSolid.Optimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=true \
              samples/shield-halved-solid.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff integrity-check/ShieldSolid.Optimized.kt samples/ShieldSolid.optimized.kt
        if [[ -z "$?" ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify complex svg conversion without optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/Illustration.NonOptimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=false \
              samples/illustration.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff integrity-check/Illustration.NonOptimized.kt samples/Illustration.nonoptimized.kt
        if [[ -z "$?" ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify complex svg conversion with optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/Illustration.Optimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=true \
              samples/illustration.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff integrity-check/Illustration.Optimized.kt samples/Illustration.optimized.kt
        if [[ -z "$?" ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi
